### ISSUE TITLE
1.dex阿伏伽德罗常微应为阿伏伽德罗常数

### ISSUE THREAD

**Issue by l1t1** [jamesfang8499/physics2#1]
我们在化学课中学过，1摩尔\footnote{摩尔简称摩，国际符号是mol}
的任
何物质，其中含有的粒子数相同，都等于12克碳-12中含有
的原子数，这个数叫做\textbf{阿伏伽德罗常微}．

**Comment by jamesfang8499** [comment]
多谢指正！
